version: '2'
services:
  odoo_client:
    build: .
    image: img_odoo_12
    container_name: cont_clientes_odoo_12
    depends_on:
      - db2_clientes
    volumes:
      - "data-odoo_client:/filestore"
      - "./src:/opt/odoo"
      - "./addons_mannol:/opt/addons_mannol"
      - "./addons_konos:/opt/addons_konos"
      - "./addons_enterprise:/opt/addons_enterprise"
      - "./addons:/opt/addons"
    environment:
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_DB_HOST=db
      - ODOO_ADMIN_PASSWORD=randompass
    ports:
      - "8888:8069"
      - "8889:8072"
    restart: always
    command: "/opt/odoo/odoo-bin -c /opt/odoo/.odoorc"
    #command: "/opt/odoo/odoo-bin -c /opt/odoo/.odoorc -d odoodb -i base"
    #command: "tail -f /dev/null"
    networks: 
      - red-odoo12-client
  db2_clientes:
    image: postgres:13
    container_name: odoo12_db_12_clientes
    shm_size: 4gb
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PG_SYSTEM_SHARED_BUFFERS=256MB
      - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
      - PG_SYSTEM_WAL_BUFFERS=8MB
      - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
    volumes:
      - "data-db2_clientes:/var/lib/postgresql/data"
    ports:
      - "5488:5432"
    restart: always
    networks: 
      - red-odoo12-client
      
networks:
   red-odoo12-client:
  
volumes:
  data-odoo_client:
  data-db2_clientes:
